### PR TITLE
Somali translation

### PR DESCRIPTION
**Pull request by 0xD7ba952CE8A0976e8d9852b7649bf01c30146**
I translated the requested informational text into Somali. The only material changes in the content are a [direct link](https://drive.google.com/file/d/0B4NP5H8LMBO4dHVlZkV1U0ZaU0E/view?usp=sharing) to the Somali document in the folder instead of the Arabic and Farsi ones, and a link to what I assume is going to be auto-generated Somali page under "Turjumaadka af Soomaali", similar to the "الترجمة العربية".

Let me know if any changes or fixes needed to be made.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thank you! This is great. I merged it and included a link

**Comment by RichardLitt** [comment]
Does that look alright to you? It should be live by now.

**Comment by 0xD7ba952CE8A0976e8d9852b7649bf01c30146** [comment]
Yup! only things I'd change:

I realized I missed the first line. "Fight the #MuslimBan Right Now" in Somali would be "La dagaal #MuslimBan-ka hadda"

Under English section at the end for "those who want to help":
1. Md formatting on 9 looks a little off, missing a closing **
2. last link on 5 appears to be misformatted

Also on the front page, technically it's "Af Soomaali" not just "Soomaali"

Thanks for all the help!

**Comment by RichardLitt** [comment]
Awesome. Fixed tose. I didn't see the last link that was misformatted - Which link was it?

**Comment by RichardLitt** [comment]
Does "Turjumaadka af Soomaali" work?

**Comment by 0xD7ba952CE8A0976e8d9852b7649bf01c30146** [comment]
Yup, turjumaadka af Soomaali is fine -- literally means "the Somali language translation".

The broken link is: 

> `Or <a href=”https://jezebel.com/a-list-of-organizations-dedicated-to-helping-immigrants-1791772883”_blank”>take a look at this comprehensive list</a>.`

**Comment by RichardLitt** [comment]
Fixed! Thank you.

**Pull request merged**
